language: node_js
node_js:
  - lts/dubnium
  - node
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: IAS1yMQlDgJCNZHdbOPj4eXFU1A/1ZYDD/1+tX6DAaWbi2NPfOjKcJ73rlILKglxqRNW1z7GsIlNN1+eXRfyKCVI1NZkxBbR6oIzlVQwl9DCk3MLVsqO3LqJV+7aPyiKdcZNAKg+gw3WzveZZiaUhb10LIs5ruIop/gFS4Tm11yx4Dhe4szwfKuLwv0yIAcu8+tA2w80XL24u/2RvWrNDCqce6zhLFihFCxOU0buE6FaLZiRL8pcMSK1f55PaXNHsQez54vfe21BYiMq/I9fGsWSOWYjcp6IBDgoGsiBAl7PD+opZECI0dO8Ux6AwIThdUVUk8EMVDfK/lEayEVyiyl79cfqXAerMk7HPlQ18NIJZhNoeVEHbDs0sgIBZAl/AQkUpktcbw8pYCL4PDYY1ZxbOYZ1Lt0cDVkrZFUBI9zEI/v5nyp0OJzsknbxcdsWUWGySxkDlb/Cpi4w4Me/XCHQVRlYUgDcdiNst+h7Rax9UuyzTFHnAerOvEaCgUevFOoKoZWyU+WuFdiNwk8CroCAJdGRl4bgQGZHxPFJUsWDAPdHIBO56k0L3fZ6t/uiwkAYNxI+/vwuzDhf95xHraZEx/GYb9Y5S3bzmHRqpUdJiggjPu8iZ3yQXaJ6wf/wAhBs8lyIwbQbPS3Th0qQzN6HnbEOd6ERasjU/AcgdFI=
  file:
    - 'aria-attributes.js'
    - 'aria-attributes.min.js'
  on:
    tags: true
